name: Run build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - deploy
    types: [closed]

jobs:
  build-android:
    if: github.event_type == 'push' || github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node dependencies
        run: echo '${{ toJSON(github) }}'
