name: Run build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node dependencies
        run: cat << EOF ${{ toJSON(github) }} EOF
