name: Run build

on:
  push:
    branches:
      - main
      - development

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy release
        if: github.ref_name == 'main'
        run: echo 'Copy release'

      - name: Copy dev
        if: github.ref_name == 'development'
        run: echo 'Copy dev'

      - name: Install node dependencies
        run: echo '${{ toJSON(github) }}'
